# Generated by Django 5.2.5 on 2026-08-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='connectivity',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_build_time',
            field=models.CharField(blank=True, default='1-2 Hours', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='microcontroller',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code_language',
            field=models.CharField(choices=[('cpp', 'C / C++ (Arduino)'), ('python', 'Python / MicroPython'), ('rust', 'Rust'), ('c', 'Pure C'), ('json', 'JSON / Config')], default='cpp', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='projects/attachments/')),
                ('file_type', models.CharField(choices=[('schematic', 'Schematic / Circuit Diagram'), ('gerber', 'Gerber PCB Files (Zip)'), ('firmware', 'Firmware / Binary / Hex'), ('cad_3d', '3D CAD / STL File'), ('datasheet', 'PDF Datasheet'), ('other', 'Other Asset')], default='other', max_length=30)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketplace.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, default='', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier_url', models.URLField(blank=True, default='')),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='marketplace.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
