# Generated by Django 5.2.5 on 2026-08-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_project_connectivity_project_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payhere_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(default='payhere', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tier_type',
            field=models.CharField(default='digital', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_courier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='LKR', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Visa / Mastercard', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('paid', 'Paid & Processing'), ('shipped', 'Shipped with Courier'), ('delivered', 'Delivered / Completed'), ('cancelled', 'Cancelled / Refunded')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ProjectTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_type', models.CharField(choices=[('digital', 'Digital Blueprint & Firmware'), ('kit', 'DIY Electronic Parts Kit'), ('assembled', 'Assembled & Tested Hardware Unit')], default='digital', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='LKR', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('requires_shipping', models.BooleanField(default=False)),
                ('stock_quantity', models.IntegerField(default=-1)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='marketplace.project')),
            ],
            options={
                'ordering': ['price', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.projecttier'),
        ),
    ]
