# Generated by Django 5.2.5 on 2026-08-17 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_hardwarebounty_chatmessage_bountyproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=35)),
                ('event_type', models.CharField(choices=[('order_created', 'Order Placed & Confirmed'), ('order_shipped', 'Order Shipped / Courier In-Transit'), ('order_delivered', 'Order Delivered'), ('bounty_proposal', 'New Maker Proposal / Bid'), ('bounty_awarded', 'Bounty Proposal Awarded'), ('chat_message', 'Live Chat Inquiry / Direct Ping'), ('test_sms', 'Test Verification SMS')], max_length=50)),
                ('message', models.TextField()),
                ('gateway', models.CharField(default='twilio', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent / Delivered'), ('mock_delivered', 'Mock Delivered (Console)'), ('failed', 'Failed'), ('queued', 'Queued')], default='sent', max_length=25)),
                ('gateway_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
