# Generated by Django 5.2.5 on 2026-08-19 18:32

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_notificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectbomitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='bountyproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bountyproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('accepted', 'Accepted / Awarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='chat/attachments/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='hardwarebounty',
            name='budget',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='hardwarebounty',
            name='connectivity',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hardwarebounty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hardwarebounty',
            name='deliverables_needed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hardwarebounty',
            name='preferred_mcu',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='hardwarebounty',
            name='status',
            field=models.CharField(choices=[('open', 'Open for Bids'), ('in_progress', 'In Progress / Awarded'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('inactive', 'Inactive'), ('closed', 'Closed / Cancelled')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='projects/attachments/'),
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='file_type',
            field=models.CharField(choices=[('zip', 'ZIP Archive'), ('pdf', 'PDF Document'), ('stl', '3D STL Model'), ('hex', 'HEX / Firmware'), ('bin', 'Binary Firmware'), ('gerber', 'Gerber PCB Archive'), ('schematic', 'Circuit Schematic'), ('datasheet', 'PDF Datasheet'), ('other', 'Other Asset')], default='other', max_length=30),
        ),
        migrations.AddIndex(
            model_name='bountyproposal',
            index=models.Index(fields=['bounty', 'status'], name='marketplace_bounty__f19cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='bountyproposal',
            index=models.Index(fields=['maker', '-created_at'], name='marketplace_maker_i_9a30b7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'recipient', '-created_at'], name='marketplace_sender__dd9a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['recipient', 'is_read'], name='marketplace_recipie_942e51_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarebounty',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_395947_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarebounty',
            index=models.Index(fields=['client', '-created_at'], name='marketplace_client__6d9628_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarebounty',
            index=models.Index(fields=['awarded_maker', '-created_at'], name='marketplace_awarded_9e987e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='marketplace_buyer_i_dfa750_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', '-created_at'], name='marketplace_seller__970086_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_04e7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['transaction_id'], name='marketplace_transac_8065c1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='marketplace_status_6dbfe9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'status'], name='marketplace_categor_7d1ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['featured', 'status'], name='marketplace_feature_42ee30_idx'),
        ),
    ]
