# Generated by Django 5.2.5 on 2026-08-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_sms_bounties',
            field=models.BooleanField(default=True, help_text='Receive SMS alerts on bounty bids and awards'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_sms_chat',
            field=models.BooleanField(default=True, help_text='Receive SMS alerts for unread maker inquiries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_sms_orders',
            field=models.BooleanField(default=True, help_text='Receive SMS alerts on purchases and shipments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number with country code (e.g. +94771234567 or 0771234567)', max_length=30),
        ),
    ]
